### ISSUE TITLE
Not issue, but a wish ))

### ISSUE THREAD

**Issue by varlesh** [kotelnik/plasma-applet-resources-monitor#1]
You're a good developer and create a great widgets for KDE 5. You can create sensors widget for CPU,HDD and GPU?
There is a version similar widget for KDE 4 - https://github.com/trifling/thermal-plasma4

**Comment by kotelnik** [comment]
Thank you for trusting in me as a good developer but the truth is I have a very little experience with C++. I definitly will dig in C++ widget backends to be able to write better widgets but it will take time. I'll try to get something done or at least started till the end of this week. My personal goal for now is Redshift Plasmoid (I used it in KDE4) and probably the sensors one because it should be quite easy when one get behind the first obstacles... And thanks for the link. I'll check it out.

**Comment by varlesh** [comment]
Good luck and thank you very much for your work!
